name: Manual Initial History Load

on:
  workflow_dispatch: # Дозволяє ручний запуск з вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Initial History Load
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run init-history
